version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: llm_chat_interface_frontend
    ports:
      - "3000:80"  # HTTP
      - "3443:443" # HTTPS
    volumes:
      - ./certs/prod:/etc/nginx/certs:ro
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - APP_ENV=production
      - VITE_API_URL=https://192.168.0.166:8443
      - USE_HTTPS=true
      - DOCKER=true

  backend:
    build:
      context: ./backend
    container_name: llm_chat_interface_backend
    ports:
      - "8000:8000"  # HTTP
      - "8443:8443"  # HTTPS
    volumes:
      - ./certs:/app/certs:ro
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - DOCKER=true
      - USE_HTTPS=true
      - CORS_ORIGINS=https://192.168.0.166:3443,https://yourdomain.com
      - SERVER_IP=192.168.0.166
      - DATABASE_URL=postgresql://${POSTGRES_USER:-prod_user}:${POSTGRES_PASSWORD:-prod_password}@postgres:5432/${POSTGRES_DB:-app_db}
    depends_on:
      - postgres
    command: ["python", "run.py"]

  # Postgres section remains unchanged